### PR TITLE
Added compressor back in >= 0.0.4

### LINKED ISSUE #3: Issue with files being there... Errno::ENOENT: No such file or directory
Removing the gem and the rakefile additions and the project builds perfectly (albeit slowly)

``` bash
 |2.1.0| OTGApps in ~/Documents/Rickert/dropzones
± |master ✗| → bundle
Using rake 10.4.2
Using bundler 1.7.4
Using methadone 1.9.0
Using ProMotion 2.3.0 from git://github.com/clearsightstudio/ProMotion.git (at master)
Using ProMotion-map 0.7.0
Using ruby_motion_query 1.3.5
Using RedAlert 1.0
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.6.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using claide 0.8.1
Using fuzzy_match 2.0.4
Using nap 0.8.0
Using cocoapods-core 0.37.0
Using cocoapods-downloader 0.9.0
Using cocoapods-plugins 0.4.2
Using netrc 0.7.8
Using cocoapods-trunk 0.6.0
Using cocoapods-try 0.4.3
Using colored 1.2
Using escape 0.0.4
Using molinillo 0.2.3
Using xcodeproj 0.24.1
Using cocoapods 0.37.0
Using motion-cocoapods 1.7.0
Using motion-require 0.2.0
Using afmotion 2.5
Using bubble-wrap-http 1.7.1
Using bubble-wrap 1.7.1 from git://github.com/cognitiveflux/BubbleWrap.git (at CLLocationManagerDelegate_didUpdateLocations)
Using compressor 0.0.3
Using motion-appstore 1.0.6
Using motion-concierge 0.0.2
Using motion-support 0.2.6
Using motion_print 1.0.0
Using reset-sim 1.0
Using newclear 1.1
Using rake-hooks 1.2.3
Using redpotion 1.1.5
Using sugarcube 3.3.5
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

 |2.1.0| OTGApps in ~/Documents/Rickert/dropzones
± |master ✗| → rake pod:install
Updating spec repo `master`
Already up-to-date.
    Concat /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-1.rb
    Concat /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-2.rb
    Concat /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-3.rb

 |2.1.0| OTGApps in ~/Documents/Rickert/dropzones
± |master ✗| → rake
    Concat /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-1.rb
    Concat /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-2.rb
    Concat /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-3.rb
running prebuild
     Build ./build/iPhoneSimulator-7.1-Development
     Build ./Pods.xcodeproj [AFNetworking - Release]
   Compile ./AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
   Compile ./AFNetworking/AFNetworking/AFURLRequestSerialization.m
   Compile ./AFNetworking/AFNetworking/AFHTTPSessionManager.m
   Compile ./AFNetworking/AFNetworking/AFNetworkReachabilityManager.m
   Compile ./AFNetworking/AFNetworking/AFHTTPRequestOperationManager.m
   Compile ./AFNetworking/AFNetworking/AFSecurityPolicy.m
   Compile ./AFNetworking/AFNetworking/AFURLConnectionOperation.m
   Compile ./AFNetworking/AFNetworking/AFHTTPRequestOperation.m
   Compile ./AFNetworking/AFNetworking/AFURLResponseSerialization.m
   Compile ./AFNetworking/AFNetworking/AFURLSessionManager.m
   Compile ./Target Support Files/Pods-AFNetworking/Pods-AFNetworking-dummy.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIAlertView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIButton+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIImageView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIProgressView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIRefreshControl+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIWebView+AFNetworking.m
   Compile ./AFNetworking/AFNetworking/AFHTTPRequestOperation.m
   Compile ./AFNetworking/AFNetworking/AFHTTPRequestOperationManager.m
   Compile ./AFNetworking/AFNetworking/AFHTTPSessionManager.m
   Compile ./AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
   Compile ./AFNetworking/AFNetworking/AFNetworkReachabilityManager.m
   Compile ./AFNetworking/AFNetworking/AFSecurityPolicy.m
   Compile ./AFNetworking/AFNetworking/AFURLConnectionOperation.m
   Compile ./AFNetworking/AFNetworking/AFURLRequestSerialization.m
   Compile ./AFNetworking/AFNetworking/AFURLResponseSerialization.m
   Compile ./AFNetworking/AFNetworking/AFURLSessionManager.m
   Compile ./Target Support Files/Pods-AFNetworking/Pods-AFNetworking-dummy.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIAlertView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIButton+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIImageView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIProgressView+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIRefreshControl+AFNetworking.m
   Compile ./AFNetworking/UIKit+AFNetworking/UIWebView+AFNetworking.m
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/x86_64/libPods-AFNetworking.a
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/libPods-AFNetworking.a
     Build ./Pods.xcodeproj [Appirater - Release]
      Copy ./Appirater/ar.lproj
      Copy ./Appirater/ca.lproj
      Copy ./Appirater/cs.lproj
      Copy ./Appirater/da.lproj
      Copy ./Appirater/de.lproj
      Copy ./Appirater/el.lproj
      Copy ./Appirater/en.lproj
      Copy ./Appirater/es.lproj
      Copy ./Appirater/fi.lproj
      Copy ./Appirater/fr.lproj
      Copy ./Appirater/he.lproj
      Copy ./Appirater/hu.lproj
      Copy ./Appirater/id.lproj
      Copy ./Appirater/it.lproj
      Copy ./Appirater/ja.lproj
      Copy ./Appirater/ko.lproj
      Copy ./Appirater/ms.lproj
      Copy ./Appirater/nl.lproj
      Copy ./Appirater/nb.lproj
      Copy ./Appirater/pl.lproj
      Copy ./Appirater/pt-BR.lproj
      Copy ./Appirater/pt.lproj
      Copy ./Appirater/ro.lproj
      Copy ./Appirater/ru.lproj
      Copy ./Appirater/sk.lproj
      Copy ./Appirater/sv.lproj
      Copy ./Appirater/th.lproj
      Copy ./Appirater/tr.lproj
      Copy ./Appirater/uk.lproj
      Copy ./Appirater/vi.lproj
      Copy ./Appirater/zh-Hans.lproj
      Copy ./Appirater/zh-Hant.lproj
     Build ./Pods.xcodeproj [Appirater - Release]
   Compile ./Appirater/Appirater.m
   Compile ./Target Support Files/Pods-Appirater/Pods-Appirater-dummy.m
   Compile ./Appirater/Appirater.m
   Compile ./Target Support Files/Pods-Appirater/Pods-Appirater-dummy.m
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-Appirater.build/Objects-normal/i386/libPods-Appirater.a
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-Appirater.build/Objects-normal/x86_64/libPods-Appirater.a
     Build ./Pods.xcodeproj [BFNavigationBarDrawer - Release]
   Compile ./BFNavigationBarDrawer/BFNavigationBarDrawer/BFNavigationBarDrawer.m
   Compile ./Target Support Files/Pods-BFNavigationBarDrawer/Pods-BFNavigationBarDrawer-dummy.m
   Compile ./BFNavigationBarDrawer/BFNavigationBarDrawer/BFNavigationBarDrawer.m
   Compile ./Target Support Files/Pods-BFNavigationBarDrawer/Pods-BFNavigationBarDrawer-dummy.m
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-BFNavigationBarDrawer.build/Objects-normal/i386/libPods-BFNavigationBarDrawer.a
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-BFNavigationBarDrawer.build/Objects-normal/x86_64/libPods-BFNavigationBarDrawer.a
     Build ./Pods.xcodeproj [OpenInChrome - Release]
   Compile ./OpenInChrome/OpenInChromeController.m
   Compile ./Target Support Files/Pods-OpenInChrome/Pods-OpenInChrome-dummy.m
   Compile ./OpenInChrome/OpenInChromeController.m
   Compile ./Target Support Files/Pods-OpenInChrome/Pods-OpenInChrome-dummy.m
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-OpenInChrome.build/Objects-normal/i386/libPods-OpenInChrome.a
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods-OpenInChrome.build/Objects-normal/x86_64/libPods-OpenInChrome.a
     Build ./Pods.xcodeproj [Pods - Release]
   Compile ./Target Support Files/Pods/Pods-dummy.m
   Compile ./Target Support Files/Pods/Pods-dummy.m
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods.build/Objects-normal/i386/libPods.a
      Link ./Users/mrickert/Documents/Rickert/dropzones/vendor/build/Pods.build/Release-iphonesimulator/Pods.build/Objects-normal/x86_64/libPods.a
     Build vendor/UIImageColorAtPoint
   Compile vendor/UIImageColorAtPoint/UIImageColorAtPoint.m
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: libUIImageColorAtPoint.a for architecture: i386 the table of contents is empty (no object file members in the library define global symbols)
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: libUIImageColorAtPoint.a for architecture: x86_64 the table of contents is empty (no object file members in the library define global symbols)
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-1.rb
/Library/RubyMotion/lib/motion/project/dependency.rb:60:in `read'
/Library/RubyMotion/lib/motion/project/dependency.rb:60:in `block in run'
/Library/RubyMotion/lib/motion/project/dependency.rb:59:in `each'
/Library/RubyMotion/lib/motion/project/dependency.rb:59:in `run'
/Library/RubyMotion/lib/motion/project/builder.rb:167:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by jamonholmgren**
Fixes https://github.com/jamonholmgren/compressor/issues/3.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
One nice side effect of Compressor that I really like is being able to search all my gems for method definitions. Cmd + Shift + F "def some_method" shows me results from all my gems too. :grin:

**Comment by markrickert** [comment]
trying it out right now ;)

**Comment by markrickert** [comment]
wonder why this happens?

``` bash
   Compile /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-3.rb
   Compile /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-2.rb
   Compile /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/bundler/gems/BubbleWrap-0a89cf389683/motion/location/pollute.rb
   Compile ./app/geojson.rb
   Compile ./app/screens/dz_detail_screen.rb
   Compile ./app/models/distance.rb
   Compile ./app/screens/concerns/open_dz_screen.rb
   Compile ./app/screens/filters/filter_detail_screen.rb
   Compile ./app/models/states.rb
   Compile /Users/mrickert/Documents/Rickert/dropzones/build/app-concatenated-1.rb
```

... 3... 2... some other stuff ... 1!

**Comment by markrickert** [comment]
Now I get fun error messages like this:

``` bash
2015-05-21 17:31:45.189 Dropzones[17883:5149852] app-concatenated-3.rb:1892:in `editable?': undefined method `each' for nil:NilClass (NoMethodError)
    from app-concatenated-3.rb:1898:in `set_up_accessibility'
    from app-concatenated-3.rb:2177:in `screen_setup'
    from app-concatenated-3.rb:558:in `try:'
    from app-concatenated-3.rb:1326:in `screen_init:'
    from 4_aircraft_screen.rb:14:in `show_dzs:'
    from app-concatenated-3.rb:1936:in `trigger_action:'
    from app-concatenated-3.rb:2056:in `tableView:didSelectRowAtIndexPath:'
```

**Comment by jamonholmgren** [comment]
@markrickert Yeah, I actually like the fun error messages because I just copy the `app-concatenated-3.rb:1898` into sublime's quick switcher and it shows me the code. I don't have to go look at the gem source. Oddly enough, it's made me more productive.

**Comment by jamonholmgren** [comment]
But I won't be offended if you disable it. :grin:

**Pull request merged**
